// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for About documents */
interface AboutDocumentData {
  /**
   * Testo come posso aiutarti field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.testo_come_posso_aiutarti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  testo_come_posso_aiutarti: prismic.RichTextField;
  /**
   * Testo di cosa mi occupo field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.testo_di_cosa_mi_occupo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  testo_di_cosa_mi_occupo: prismic.RichTextField;
  /**
   * testo side project field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.testo_side_project
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  testo_side_project: prismic.RichTextField;
  /**
   * Foto field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.foto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  foto: prismic.ImageField<never>;
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *About → Slice Zone*
 *
 */
type AboutDocumentDataSlicesSlice = never;
/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = AboutCardSlice | ProjectCardSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.TitleField;
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = RichTextSlice | AboutCardSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Project documents */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * Sub title field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  sub_title: prismic.RichTextField;
  /**
   * Description (x card piccoline) field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * Long text (x pagina progetto) field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.long_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  long_text: prismic.RichTextField;
  /**
   * Type field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Tipologia di progetto (di default setta Editorial)
   * - **Default Value**: Editorial
   * - **API ID Path**: project.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  type: prismic.SelectField<
    "Editorial" | "Digital" | "Brand Identity",
    "filled"
  >;
  /**
   * External Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.external_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  external_image: prismic.ImageField<never>;
  /**
   * Is In Homepage field in *Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.is_in_homepage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  is_in_homepage: prismic.BooleanField;
  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField;
  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Project → Slice Zone*
 *
 */
type ProjectDocumentDataSlicesSlice =
  | DoubleHorizontallImagesSlice
  | DoubleVerticalImagesSlice
  | ImageFullSlice
  | VideoSlice
  | ProjectVideoSlice;
/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;
export type AllDocumentTypes =
  | AboutDocument
  | HomepageDocument
  | PageDocument
  | ProjectDocument;
/**
 * Primary content in AboutCard → Primary
 *
 */
interface AboutCardSliceDefaultPrimary {
  /**
   * Title field in *AboutCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_card.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
  /**
   * description field in *AboutCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_card.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
}
/**
 * Default variation for AboutCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutCardSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *AboutCard*
 *
 */
type AboutCardSliceVariation = AboutCardSliceDefault;
/**
 * AboutCard Shared Slice
 *
 * - **API ID**: `about_card`
 * - **Description**: `AboutCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutCardSlice = prismic.SharedSlice<
  "about_card",
  AboutCardSliceVariation
>;
/**
 * Primary content in DoubleHorizontallImages → Primary
 *
 */
interface DoubleHorizontallImagesSliceDefaultPrimary {
  /**
   * Prima Immagine field in *DoubleHorizontallImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_horizontall_images.primary.prima_immagine
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  prima_immagine: prismic.ImageField<never>;
  /**
   * Seconda Immagine field in *DoubleHorizontallImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_horizontall_images.primary.seconda_immagine
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  seconda_immagine: prismic.ImageField<never>;
}
/**
 * Default variation for DoubleHorizontallImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoubleHorizontallImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DoubleHorizontallImagesSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *DoubleHorizontallImages*
 *
 */
type DoubleHorizontallImagesSliceVariation =
  DoubleHorizontallImagesSliceDefault;
/**
 * DoubleHorizontallImages Shared Slice
 *
 * - **API ID**: `double_horizontall_images`
 * - **Description**: `DoubleHorizontallImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoubleHorizontallImagesSlice = prismic.SharedSlice<
  "double_horizontall_images",
  DoubleHorizontallImagesSliceVariation
>;
/**
 * Primary content in DoubleVerticalImages → Primary
 *
 */
interface DoubleVerticalImagesSliceDefaultPrimary {
  /**
   * Prima Immagine field in *DoubleVerticalImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_vertical_images.primary.prima_immagine
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  prima_immagine: prismic.ImageField<never>;
  /**
   * Seconda Immagine field in *DoubleVerticalImages → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_vertical_images.primary.seconda_immagine
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  seconda_immagine: prismic.ImageField<never>;
}
/**
 * Default variation for DoubleVerticalImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoubleVerticalImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DoubleVerticalImagesSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *DoubleVerticalImages*
 *
 */
type DoubleVerticalImagesSliceVariation = DoubleVerticalImagesSliceDefault;
/**
 * DoubleVerticalImages Shared Slice
 *
 * - **API ID**: `double_vertical_images`
 * - **Description**: `DoubleVerticalImages`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DoubleVerticalImagesSlice = prismic.SharedSlice<
  "double_vertical_images",
  DoubleVerticalImagesSliceVariation
>;
/**
 * Primary content in ImageFull → Primary
 *
 */
interface ImageFullSliceDefaultPrimary {
  /**
   * Immagine field in *ImageFull → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_full.primary.immagine
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  immagine: prismic.ImageField<never>;
}
/**
 * Default variation for ImageFull Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFullSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageFullSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ImageFull*
 *
 */
type ImageFullSliceVariation = ImageFullSliceDefault;
/**
 * ImageFull Shared Slice
 *
 * - **API ID**: `image_full`
 * - **Description**: `ImageFull`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageFullSlice = prismic.SharedSlice<
  "image_full",
  ImageFullSliceVariation
>;
/**
 * Primary content in ProjectCard → Primary
 *
 */
interface ProjectCardSliceDefaultPrimary {
  /**
   * Project field in *ProjectCard → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_card.primary.project
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  project: prismic.ContentRelationshipField<"project">;
}
/**
 * Default variation for ProjectCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectCardSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ProjectCard*
 *
 */
type ProjectCardSliceVariation = ProjectCardSliceDefault;
/**
 * ProjectCard Shared Slice
 *
 * - **API ID**: `project_card`
 * - **Description**: `ProjectCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectCardSlice = prismic.SharedSlice<
  "project_card",
  ProjectCardSliceVariation
>;
/**
 * Primary content in ProjectVideo → Primary
 *
 */
interface ProjectVideoSliceDefaultPrimary {
  /**
   * video field in *ProjectVideo → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  video: prismic.LinkToMediaField;
}
/**
 * Default variation for ProjectVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectVideoSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *ProjectVideo*
 *
 */
type ProjectVideoSliceVariation = ProjectVideoSliceDefault;
/**
 * ProjectVideo Shared Slice
 *
 * - **API ID**: `project_video`
 * - **Description**: `ProjectVideo`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProjectVideoSlice = prismic.SharedSlice<
  "project_video",
  ProjectVideoSliceVariation
>;
/**
 * Primary content in RichText → Primary
 *
 */
interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *RichText*
 *
 */
type RichTextSliceVariation = RichTextSliceDefault;
/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;
/**
 * Primary content in Video → Primary
 *
 */
interface VideoSliceDefaultPrimary {
  /**
   * Video Url field in *Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.video_url
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  video_url: prismic.EmbedField;
}
/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Video*
 *
 */
type VideoSliceVariation = VideoSliceDefault;
/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AboutDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectDocument,
      AllDocumentTypes,
      AboutCardSliceDefaultPrimary,
      AboutCardSliceDefault,
      AboutCardSliceVariation,
      AboutCardSlice,
      DoubleHorizontallImagesSliceDefaultPrimary,
      DoubleHorizontallImagesSliceDefault,
      DoubleHorizontallImagesSliceVariation,
      DoubleHorizontallImagesSlice,
      DoubleVerticalImagesSliceDefaultPrimary,
      DoubleVerticalImagesSliceDefault,
      DoubleVerticalImagesSliceVariation,
      DoubleVerticalImagesSlice,
      ImageFullSliceDefaultPrimary,
      ImageFullSliceDefault,
      ImageFullSliceVariation,
      ImageFullSlice,
      ProjectCardSliceDefaultPrimary,
      ProjectCardSliceDefault,
      ProjectCardSliceVariation,
      ProjectCardSlice,
      ProjectVideoSliceDefaultPrimary,
      ProjectVideoSliceDefault,
      ProjectVideoSliceVariation,
      ProjectVideoSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceDefault,
      RichTextSliceVariation,
      RichTextSlice,
      VideoSliceDefaultPrimary,
      VideoSliceDefault,
      VideoSliceVariation,
      VideoSlice,
    };
  }
}
