// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_card: defineAsyncComponent(() => import("./AboutCard/index.vue")),
  project_card: defineAsyncComponent(() => import("./ProjectCard/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
